#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# customer UI pre-push stages
#TODO:temp --forceExit, fix this prblem. Use the `--detectOpenHandles` to detect async operations that kept running after all tests finished
yarn test --forceExit

# Commit will be aborted
# exit 1